openapi_core/operations.py
Get the list of allowed operations from openapi_spec_validator:
https://github.com/p1c2u/openapi-spec-validator/blob/b2e439aa79c7cde932f9926f1ae124556924b10d/openapi_spec_validator/validators.py#L157
=> Use a more generic test for path item object's operations

openapi_core/components.py, openapi_core/specs.py
The specification:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#schema
clearly states that fields:
- #/info
- #/paths
- #/components
- #/components/schemas
- #/components/responses
- #/components/parameters
- #/components/requestBodies
are objects.
=> Use appropriate default values for OpenAPI object fields

openapi_core/components.py, openapi_core/operations.py, openapi_core/servers.py, openapi_core/specs.py, openapi_core/validators.py, requirements.txt, tests/integration/data/v3.0/minimal.yaml, tests/integration/data/v3.0/minimal_with_servers.yaml, tests/integration/test_minimal.py
The specification:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#oasObject
requires that if the `servers` array is not provided or empty,
its default value is an array of a single `Server Object`
with `url` of `/`.
This can only be merged after PRs #13 and #14 are merged.
=> Add the default value for the 'servers' array

openapi_core/schemas.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py
We should allow undefined types. Value for schema without type won;t be cast.
Fixes #19
=> Allow undefined schema type

.gitignore, openapi_core/__init__.py, openapi_core/schemas.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_validators.py
Currently if valid swagger syntax is used for model composition an
error will be thrown due to the lack of a type property. This was
corrected by making object the default type.
schema_type = schema_deref.get('type', 'object')
I changed the swagger definition to test for this. Now PetCreate is a
composite of PetCreatePartOne and PetCreatePartTwo. However, this
caused `test_post_pets_empty_body` to fail, which turned out to be a
bug in the required properties.
In `_unmarshal_object` the `get_all_properties` method is called to get
all properties from the subschemas. However, this is not done for
required properties, meaning that only top level required properties
will be correctly validated. I have added a
`get_all_required_properties’ to fix this.
This caused `test_get_pets` to fail. In …
=> Fixing Subschema Required Properties Validation

openapi_core/media_types.py, openapi_core/schemas.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_validators.py
=> Response JSON text as array fix

openapi_core/schema/schemas/exceptions.py, openapi_core/schema/schemas/factories.py, openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_validators.py
=> OneOf schema support

openapi_core/schema/properties/generators.py, openapi_core/schema/schemas/factories.py, openapi_core/schema/schemas/registries.py, openapi_core/schema/schemas/util.py, requirements.txt, tests/integration/data/v3.0/petstore.yaml, tests/unit/schema/test_schemas_registry.py
Fixes #31
Schema references are now lazy objects. Properties generator uses schemas registry now.
=> Lazy schema references

openapi_core/__init__.py
To make building RPMs of package easier when using ascii by default.
=> Replace unicode character for RPM build.

openapi_core/schema/operations/generators.py, openapi_core/schema/operations/models.py, tests/integration/test_petstore.py
There's a need to access endpoint tags in parsed spec. Adding this feature here.
=> Expose tags in Operation object

openapi_core/schema/schemas/factories.py, openapi_core/schema/schemas/models.py, tests/unit/schema/test_schemas.py
Add support for the following validation properties:
- multipleOf
- maximum
- exclusiveMaximum
- minimum
- exclusiveMinimum
- maxLength
- minLength
- pattern
- maxItems
- minItems
- uniqueItems
- maxProperties
- minProperties
Fixes #49
=> Add support for additional validation properties

README.rst
Rename from openapi_core.validators to openapi_core.shortcuts
=> Fix README example

openapi_core/schema/schemas/util.py, requirements.txt, requirements_2.7.txt, setup.py, tests/unit/schema/test_schemas.py
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types
Note: `jsonschema` uses the same library if it's installed (and otherwise doesn't validate `date-time`).
cc @p1c2u
=> openapi 3.0 defines date-time format to be rfc3339

openapi_core/schema/schemas/util.py
`strict_rfc3339.rfc3339_to_timestamp()` is tz aware
`datetime.datetime.fromtimestamp` is not
this causes  the test `test_string_format_datetime` to fail on
system that are not on utc
=> fix test for non utc systems.

openapi_core/schema/schemas/enums.py, openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/unit/schema/test_schemas.py
This introduces the compatibility with uuid formatted strings. Although it's not a predefined format in the standard, it's predicted as a possible custom format, so it makes sense to implement it since Python supports this as a type in the stdlib.
=> Accepting uuid string format and validating accordingly.

openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_validators.py, tests/unit/schema/test_schemas.py
=> byte string format

openapi_core/schema/parameters/models.py, openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_validators.py, tests/unit/schema/test_schemas.py
Strict validation of raw value type.
Enabled for media type only. Parameters are disabled for now (backward compatibility). Parameters type strict validation should be enabled by default in version 1.0.
Fixes #105
=> Raw value type strict validation

openapi_core/__init__.py, openapi_core/schema/schemas/factories.py, openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/unit/schema/test_schemas.py
* Default is true like in specification
* When is set false, it works like in past
* Object with types works
It reslove Issue https://github.com/p1c2u/openapi-core/issues/67
=> Object additionalProperties support

openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/util.py, tests/unit/schema/test_schemas.py
Before this change, if a UUID instance got received as value in the Schema, it was breaking the unmarshal because UUID instances can't be used as values to instantiate other UUIDs.
An example of where this might happen is if you define a parameter with uuid format in a spec for a Flask app, and then use the `<uuid>` converter in the route path (for the Flask router), which converts the parameter to a UUID instance before it reaches the unmarshalling step.
=> Properly formatting UUID if value to be unmarshalled is already a UUID.

openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/util.py, tests/integration/test_petstore.py, tests/integration/test_validators.py, tests/unit/schema/test_schemas.py
Previously `byte` format had to be binary type on input and output of unmarshalling. Now it should be text type.
=> String byte format fix

openapi_core/schema/schemas/models.py, tests/unit/schema/test_schemas.py
This is important because it does the correct validation over items that
are restricted in "oneOf", so that it's possible to use schemas that are
superset of one another as items of "oneOf".
=> Fix #124: Checking "additionalProperties" in "oneOf" items.

openapi_core/schema/schemas/models.py, tests/unit/schema/test_schemas.py
`password` is a valid OpenAPIv3 string format, that is used as a UI hint
for frontend clients to mask the input field.
It was already present in the `SchemaFormat` enum, but it was not
handled in `_unmarshal_string` that uses `STRING_FORMAT_CALLABLE_GETTER`
to decide how to unmarshal a string, which would result in an error like
this one:
```
Traceback (most recent call last):
[... snip ...]
File ".venv/lib/python3.7/site-packages/openapi_core/validation/request/validators.py", line 37, in validate
body, body_errors = self._get_body(request, operation)
File ".venv/lib/python3.7/site-packages/openapi_core/validation/request/validators.py", line 82, in _get_body
body = media_type.unmarshal(raw_body, self.custom_formatters)
File ".venv/lib/python3.7/site-packages/openapi_core/schema/media_typ …
```
=> Add support for `password` string format

openapi_core/schema/paths/generators.py, openapi_core/schema/paths/models.py, tests/integration/data/v3.0/path_param.yaml, tests/integration/test_path_params.py
=> add support for path-level parameters

openapi_core/schema/links/generators.py, openapi_core/schema/links/models.py, openapi_core/schema/responses/generators.py, tests/integration/data/v3.0/links.yaml, tests/integration/test_link_spec.py, tests/unit/schema/test_links.py
=> add support for "links" in Response

openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/util.py, tests/unit/schema/test_schemas.py
The `integer_types` is always a tuple. When checking
if an instance is a number it fails because it's doing a comparison against a tuple
instead of real type.
➜ python -c "from six import integer_types;import sys;print(integer_types);print(sys.version)"
(<type 'int'>, <type 'long'>)
2.7.16 (default, Apr  6 2019, 01:42:57)
[GCC 8.3.0]
➜ python3 -c "from six import integer_types;import sys;print(integer_types);print(sys.version)"
(<class 'int'>,)
3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0]
And spec defines a number as both int and float https://swagger.io/docs/specification/data-models/data-types/#numbers so both validators need to support both types.
=> Fix number validator

.travis.yml, setup.py
https://www.python.org/dev/peps/pep-0429/#id4
=> Removing Python 3.4 from testing. It is no longer supported.

openapi_core/schema/schemas/models.py, tests/integration/test_petstore.py, tests/unit/schema/test_schemas.py
This is a rebased version of my original [PR](https://github.com/p1c2u/openapi-core/pull/114) rebased on p1c2u/master to get rid of the unnecessary strict validation changes. This pull requests adds support for various cases of oneOf in combination with a SchemaType.ANY schema that currently fail to unmarshal correctly, for example...
```yaml
Polymorphic:
oneOf:
Values:
type:  array
items:
type: string
Value:
type: string
```
=> Add support for one-of with any type

openapi_core/wrappers/flask.py, tests/integration/data/v3.0/flask_wrapper.yaml, tests/integration/test_wrappers.py
I believe this is a partial fix for #35 (see also #93). It doesn't attempt to solve the general case of accommodating all the possible routers out there. Instead, this is a limited set of changes confined to the `wrappers.flask` module that uses a regex to transform the Flask URL variables into OpenAPI path parameters.
Thanks for your work on this very useful library.
=> Modify FlaskOpenAPIRequest to accomodate path variables

openapi_core/schema/paths/exceptions.py, openapi_core/schema/specs/models.py, openapi_core/validation/request/models.py, openapi_core/validation/request/validators.py, tests/integration/test_minimal.py, tests/integration/test_validators.py
Fixes #140
@gweis thanks for tests
=> Parameters on path item object support

openapi_core/validation/request/validators.py, tests/integration/test_validators.py
Hi. This is a follow up on #140 and #144.
The fix in #144 is good enough for me and solves my use case. (Thanks again @p1c2u)
However I thought I play around a bit and test overriding parameters. Here are two very simple (and hacky) test cases to demonstrate that. 
The issue of overriding `Path Item Parameters` with `Operation Parameters` is a bit more complex though. First it is possible to create an invalid `Spec` object by overriding a parameter with same name but different `in` attribute. The second part is parameter validation, which should only validate with the overridden parameter definition from the `Operation` object.
I believe it is a rather rare use case to override parameters, but I thought I'll put it up here. It does not hinder me using this fantastic library and I know …
=> very simple and hacky path item parameter override test

openapi_core/schema/parameters/models.py, openapi_core/schema/schemas/models.py
Allows parameters to be strictly unmarshalled
=> Separate cast and unmarshal

openapi_core/schema/media_types/models.py, openapi_core/schema/parameters/models.py, openapi_core/schema/schemas/_format.py, openapi_core/schema/schemas/_types.py, openapi_core/schema/schemas/_validators.py, openapi_core/schema/schemas/exceptions.py, openapi_core/schema/schemas/factories.py, openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/types.py, openapi_core/schema/schemas/unmarshallers.py, openapi_core/schema/schemas/validators.py, openapi_core/schema/specs/factories.py, openapi_core/schema/specs/models.py, openapi_core/shortcuts.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/validators.py, requirements.txt, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_validators.py, tests/unit/schema/test_media_types.py, tests/unit/schema/test_parameters.py, tests/unit/schema/test_schemas.py
New OAS validation will fix many issues with schema validation in openapi core.
Fixes #155 #147 #129 #127 #122 #115 #103 #77
Partially fixes #139 #100 (see https://github.com/p1c2u/openapi-core/pull/157/files#diff-c509eb72d0b1058bf79f8f2ac563b7afR231).
=> OAS validation with JSONSchema

openapi_core/schema/media_types/models.py, openapi_core/schema/parameters/exceptions.py, openapi_core/schema/parameters/models.py, openapi_core/schema/schemas/exceptions.py, openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/unmarshallers.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/validators.py, tests/integration/validation/test_petstore.py, tests/unit/schema/test_schemas.py
=> Schema exceptions refactor

openapi_core/schema/external_docs/factories.py, openapi_core/schema/external_docs/models.py, openapi_core/schema/operations/generators.py, openapi_core/schema/operations/models.py, openapi_core/schema/security/factories.py, openapi_core/schema/security/models.py, openapi_core/schema/servers/generators.py, openapi_core/schema/servers/models.py, openapi_core/schema/specs/factories.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/schema/test_spec.py
More operations fields:
- summary
- description
- externalDocs
- security
- servers
Fixes #163
=> Operations fields

openapi_core/schema/schemas/exceptions.py, openapi_core/schema/schemas/models.py, tests/integration/validation/test_petstore.py
=> Validation schema errors iter fix

openapi_core/schema/parameters/models.py, requirements_dev.txt, setup.cfg, tests/integration/validation/test_validators.py
`webob` (used by pyramid) 's multidict protocol does not have `getlist` method, use `getall` instead of `getlist`.
=> webob support

openapi_core/casting/schemas/casters.py, openapi_core/casting/schemas/exceptions.py, openapi_core/casting/schemas/factories.py, openapi_core/casting/schemas/util.py, openapi_core/schema/media_types/models.py, openapi_core/schema/parameters/models.py, openapi_core/schema/schemas/exceptions.py, openapi_core/schema/schemas/models.py
Next step in package cleanup/refactoring
=> Move casters to separate subpackage

README.rst, openapi_core/schema/media_types/models.py, openapi_core/schema/parameters/models.py, openapi_core/unmarshalling/schemas/factories.py, openapi_core/validation/request/shortcuts.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/shortcuts.py, openapi_core/validation/response/validators.py, tests/integration/validation/test_petstore.py, tests/integration/validation/test_validators.py, tests/unit/schema/test_media_types.py, tests/unit/schema/test_parameters.py, tests/unit/unmarshalling/test_unmarshal.py, tests/unit/validation/test_request_shortcuts.py, tests/unit/validation/test_response_shortcuts.py
* Deprecated `validate_parameters `, `validate_body` and `validate_data` shortcuts
* get rid of `InvalidMediaTypeValue ` exception from unmarshalling process. Now it returns original `InvalidSchemaValue ` exception
=> Move unmarshal out of schema models

openapi_core/schema/contacts/factories.py, openapi_core/schema/contacts/models.py, openapi_core/schema/infos/factories.py, openapi_core/schema/infos/models.py, openapi_core/schema/licenses/factories.py, openapi_core/schema/licenses/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/schema/test_spec.py
=> Missing Info models

openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py
=> Free-form objects unmarshal

setup.cfg
=> werkzeug missing dependency fix

README.rst, openapi_core/contrib/requests/__init__.py, openapi_core/contrib/requests/requests.py, openapi_core/contrib/requests/responses.py, openapi_core/validation/request/datatypes.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/validators.py, requirements_dev.txt, setup.cfg, tests/integration/contrib/requests/conftest.py, tests/integration/contrib/requests/data/v3.0/requests_factory.yaml, tests/integration/contrib/requests/test_requests_requests.py, tests/integration/contrib/requests/test_requests_validation.py, tests/integration/validation/test_minimal.py, tests/integration/validation/test_validators.py
After finder introduction with path with variables resolving it's finally possible to implement requests integration.
1. The request validator checks for a path variables in the request object.
2. If empty gets it from the finder's path result.
Part of ##32
=> Requests integration

openapi_core/security/providers.py, openapi_core/security/util.py, tests/unit/security/test_providers.py
=> b64decode issue29427 fix

setup.cfg
Refs https://github.com/python-poetry/poetry/pull/2144#issuecomment-596221732
Fixes #206
=> Fix to force ConfigParser to correctly parse extra requirements

openapi_core/schema/servers/models.py, openapi_core/templating/paths/finders.py, tests/unit/templating/test_paths_finders.py
=> Paths finder relative url and simple paths check fix

README.rst
Great work on this library, it's really cool!
I was looking for a way to add custom formatters and found the `custom_formatters` argument. I found it very useful, so I thought I'd add it to the documentation.
I'm not sure if the usage example I gave is the best (are you supposed to provide both `validate` and `unmarshal` in this case?) so I'd be happy to get suggestions on how to improve it.
I didn't find any contribution guidelines so I hope I'm doing this right!
Best regards,
@chreke
=> Add documentation for custom formatters

openapi_core/contrib/requests/responses.py, requirements_dev.txt, setup.cfg, tests/integration/contrib/requests/conftest.py, tests/integration/contrib/requests/test_requests_responses.py, tests/integration/contrib/requests/test_requests_validation.py
Requests.response attribute `raw` is filelike object. During response validation it fails due to DeserializationError. It is the way the response.raw is treated like string or bytes object, witch it isn't.
`content` attribute on the other hand does exatctly wahat is expected.
=> Fix Requests.response factory

openapi_core/contrib/django/requests.py, openapi_core/validation/request/datatypes.py, tests/unit/security/test_providers.py
=> Case insensitive headers fix

openapi_core/security/providers.py, openapi_core/security/util.py, tests/integration/validation/test_validators.py, tests/unit/security/test_providers.py
Let caller handle/decode credentials.
Fixes #223
=> Security HTTP provider fix

openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py
=> Unmarshalling nullable objects

openapi_core/unmarshalling/schemas/unmarshallers.py, openapi_core/unmarshalling/schemas/util.py, requirements.txt, requirements_2.7.txt, setup.cfg, tests/integration/validation/test_petstore.py, tests/unit/unmarshalling/test_unmarshal.py
=> Date-time format unmarshal  tz fix

openapi_core/templating/util.py, tests/unit/templating/test_util.py
Adds PathParameter extra type (no slash chars)
Extended parser uses PathParameter as default type.
Fixes #226
=> Templating parser path parameter search fix

README.rst, openapi_core/contrib/falcon/requests.py, tests/integration/contrib/falcon/data/v3.0/falcon_factory.yaml, tests/integration/contrib/falcon/test_falcon_validation.py
Bring main README up to date for current falcon integration. Fixes #242
=> Fix the Falcon integration to properly handle URLs with query strings.

openapi_core/schema/schemas/models.py, openapi_core/unmarshalling/schemas/factories.py
- overriding __dict__ is death for pickling.   I renamed it to __newdict__
and tweaked the one user of it, and now this part of the structure is
working fine for pickling
- there are also upstream changes in jsonschema that need to be in for the
overall success
- this allows me to create the API spec from a swagger file once (which takes
2-20s for the files I'm working with), and cache the result as a pickle file
for loading on the next startup (assuming the swagger file hasn't been
updated).  The load from pickle files takes 2-5ms.  This is an improvement
of load time by 3 orders of magnitude.
=> Small change to Schema model to allow generated specs to be picklable

openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py
See: https://github.com/p1c2u/openapi-core/issues/251
Addresses this point specifically:
```
When nullable is set for arrays (i.e. type: array & nullable: true), null value not being properly validated, instead, it raising error: 'NoneType' object is not iterable. So, the same issue that diogobaeder reported in the second post.
```
=> ArrayUnmarshaller: return None on nullable type instead of "NoneType object is not iterable" crash

openapi_core/schema/operations/generators.py, openapi_core/schema/operations/models.py, openapi_core/validation/request/validators.py, tests/integration/data/v3.0/security_override.yaml, tests/integration/schema/test_spec.py, tests/integration/validation/test_security_override.py
=> Remove security on operation level fix

openapi_core/unmarshalling/schemas/unmarshallers.py, tests/integration/data/v3.0/petstore.yaml, tests/unit/unmarshalling/test_unmarshal.py
Use allOf schemas to determine unmarshaller schema type for AnyUnmarshaller
Fixes #285
=> AnyUnmarshaller use allOf schemas

README.rst, openapi_core/schema/shortcuts.py, openapi_core/schema/specs/factories.py
Allows to disable spec validation that can improve the performance. Relates to #289
=> Spec validation customization

openapi_core/unmarshalling/schemas/factories.py
Should improve the performance. Related to #289
=> Format checker deepcopy to shallowcopy

openapi_core/unmarshalling/schemas/factories.py, openapi_core/unmarshalling/schemas/util.py, openapi_core/validation/validators.py, tests/unit/unmarshalling/test_unmarshal.py, tests/unit/unmarshalling/test_validate.py
Format checker cached in validator object. Should improve unmarshalling performance for many requests. Fixes #289
=> Format checker on validation scope

openapi_core/contrib/requests/requests.py, tests/integration/contrib/requests/data/v3.0/requests_factory.yaml, tests/integration/contrib/requests/test_requests_requests.py, tests/integration/contrib/requests/test_requests_validation.py
Use requests.PreparedRequest object to convert requests.Request into a formatted payload before converting into an OpenAPI request.
Fixes bug where one of the many requests.Request convenience methods (ex json) are used and payload is not stored in Request.data. Should also handle scenarios where persistent sessions have expected headers not applied to the request object until it is prepared and sent
=> use prepared request to format payload before converting

openapi_core/deserializing/media_types/factories.py, openapi_core/deserializing/media_types/util.py, tests/unit/deserializing/test_media_types_deserializers.py
Experimental data form media type support
Fixes #299
=> deserialize data form media type

setup.py
This fixes pip so it displays the correct license for the package.
=> Set license from __init__.py

openapi_core/contrib/falcon/compat.py, openapi_core/contrib/falcon/handlers.py, openapi_core/contrib/falcon/requests.py, openapi_core/contrib/falcon/responses.py, requirements_dev.txt, tests/integration/contrib/falcon/conftest.py, tests/integration/contrib/falcon/test_falcon_middlewares.py
Fixes #311. Makes openapi-core compatible with falcon 3.0.0
=> Bugfix 311 falcon get media error

README.rst, docs/integrations.rst
Add a link to the tornado-openapi3 project I authored which provides openapi-core validation for the Tornado web application framework.
- Project: https://github.com/correl/tornado-openapi3
- Documentation: https://tornado-openapi3.readthedocs.io/en/latest/
=> Add link to Tornado integration

openapi_core/schema/parameters.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/validation/test_petstore.py
=> Parameter simple scenarion for any schema type fix

openapi_core/exceptions.py, openapi_core/validation/request/validators.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/validation/test_petstore.py, tests/integration/validation/test_validators.py
Raises `MissingRequiredRequestBody` instead of `MissingRequestBody`
Fixes #324
=> Non required request body fix

openapi_core/deserializing/parameters/deserializers.py, openapi_core/exceptions.py, openapi_core/schema/parameters.py, openapi_core/testing/responses.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/datatypes.py, openapi_core/validation/response/validators.py, openapi_core/validation/validators.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/schema/test_spec.py, tests/integration/validation/test_petstore.py
Backward incompatible changes:
* `headers` attribute added to `OpenAPIResponse` datatype
=> Response headers support

openapi_core/__init__.py, openapi_core/schema/parameters.py, openapi_core/shortcuts.py, openapi_core/validation/request/shortcuts.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/shortcuts.py, openapi_core/validation/response/validators.py, tests/integration/validation/test_petstore.py, tests/unit/validation/test_request_shortcuts.py, tests/unit/validation/test_response_shortcuts.py
Changes
* added `RequestSecurityValidator` and `ResponseHeadersValidator`
Backward incompatibilities
* `validate_parameters`, `validate_body`, `validate_data` shortcuts replaced with `RequestParametersValidator`  `RequestBodyValidator` `ResponseDataValidator` validators
=> Validators refactor

docs/usage.rst
Hello.
This code block doesn't look good.
I fixed it.
Love,
Kamil
=> Fix  code-block formatting in usage.rst

.github/workflows/build-docs.yml, docs/conf.py, requirements_dev.txt
Hello,
In order to detect errors in the documentation, I would like to propose building the documentation on CI.
Best regards,
Kamil
=> Build documentation on CI

openapi_core/contrib/django/requests.py, tests/integration/contrib/test_django.py
Helllo.
I had a project that used a very old URL format and unfortunately, this library couldn't find the path.
```
from django.conf.urls import url
```
It turned out that this library tries to make various concatenations and matches based on this expression which obviously failed.
https://github.com/p1c2u/openapi-core/blob/512ff6b48d105351c4be730dd78c5d7c00492db1/openapi_core/templating/paths/finders.py#L49
Close: https://github.com/p1c2u/openapi-core/issues/278
Brest regards,
Kamil Breguła
=> Support basic re_path

openapi_core/casting/schemas/casters.py, openapi_core/types.py, openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py
`NoValue` type no longer needed
=> Get rid of NoValue type

openapi_core/casting/schemas/exceptions.py, openapi_core/contrib/django/requests.py, openapi_core/contrib/django/responses.py, openapi_core/contrib/falcon/requests.py, openapi_core/contrib/falcon/responses.py, openapi_core/contrib/flask/requests.py, openapi_core/contrib/flask/responses.py, openapi_core/contrib/requests/requests.py, openapi_core/contrib/requests/responses.py, openapi_core/deserializing/exceptions.py, openapi_core/deserializing/parameters/exceptions.py, openapi_core/exceptions.py, openapi_core/templating/datatypes.py, openapi_core/templating/media_types/exceptions.py, openapi_core/templating/paths/exceptions.py, openapi_core/templating/responses/exceptions.py, openapi_core/templating/responses/finders.py, openapi_core/testing/requests.py, openapi_core/testing/responses.py, openapi_core/unmarshalling/schemas/exceptions.py, openapi_core/validation/datatypes.py, openapi_core/validation/exceptions.py, openapi_core/validation/request/datatypes.py, openapi_core/validation/response/datatypes.py, requirements.txt, setup.cfg, tests/integration/contrib/flask/test_flask_requests.py, tests/integration/contrib/requests/test_requests_requests.py, tests/integration/contrib/test_django.py
Changes:
* get rid of `attrs` and use `dataclasses` backport for python 3.6
Backward incompatibilities:
* `RequestParameters`' `header` attribute as `Headers` type
* `RequestParameters`' `cookie` attribute as `ImmutableMultiDict` type
* unused `server`, `operation` and `path` attributes removed from `RequestValidationResult`
=> Dataclasses refactor

openapi_core/validation/request/datatypes.py, openapi_core/validation/request/validators.py, tests/integration/contrib/falcon/test_falcon_middlewares.py, tests/integration/contrib/flask/test_flask_decorator.py, tests/integration/validation/test_minimal.py, tests/integration/validation/test_petstore.py, tests/integration/validation/test_validators.py
* `RequestValidationResult`' `parameters` attribute as `Parameters` type
=> Request validation parameters dataclass

openapi_core/deserializing/exceptions.py, openapi_core/deserializing/media_types/deserializers.py, openapi_core/deserializing/media_types/exceptions.py, openapi_core/deserializing/media_types/factories.py, openapi_core/deserializing/parameters/deserializers.py, openapi_core/deserializing/parameters/exceptions.py, openapi_core/deserializing/parameters/factories.py, openapi_core/deserializing/parameters/util.py, tests/integration/validation/test_petstore.py, tests/integration/validation/test_validators.py, tests/unit/deserializing/test_media_types_deserializers.py, tests/unit/deserializing/test_parameters_deserializers.py
Unsupported deserializers raise warning.
* media type deserializers raise `MediaTypeDeserializeError` (which inherits from `DeserializeError `) instead of `DeserializeError` itself
* parameter deserializers raise `ParameterDeserializeError` (which inherits from `DeserializeError `) instead of `DeserializeError` itself
Backward compatibilities:
* `EmptyParameterValue` exception renamed to `EmptyQueryParameterValue`
=> Deserializing refactor

docs/integrations.rst
- Fixed grammar - replace `a` when `as a` was needed.
- Remove redundancy. Like no need to mention `Falcon` twice here when you already in the Falcon section.
```diff
- For Falcon you can use FalconOpenAPIRequest a Falcon request factory:
+ You can use `FalconOpenAPIRequest` as a Falcon request factory:
```
- Add backticks around classes
- Use single space in URLs (some had 1 and some had 2)
=> docs: update integrations.rst

openapi_core/templating/media_types/finders.py, tests/unit/templating/test_media_types_finders.py
It's possible for a response not to have a MIME type (`mimetype=None`).
Previously, this would result in an exception from within `fnmatch()`:
```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
This change guards against that condition and raises `MediaTypeNotFound`
instead. Tests have also been added for this module.
=> Handle missing MIME type in MediaTypeFinder

.github/workflows/python-test.yml, .travis.yml, pyproject.toml
Updates github action workflow, travis ci and requirements to drop python 3.6 and add python 3.10 support.
=> Drop python 3.6 support and add support for python 3.10

requirements.txt, requirements_2.7.txt, requirements_dev.txt, setup.cfg
=> pin openapi dependencies

requirements.txt, setup.cfg, tests/integration/contrib/django/data/djangoproject/testapp/views.py
=> pyyaml strict requirement fix

openapi_core/casting/schemas/casters.py, openapi_core/casting/schemas/exceptions.py, tests/unit/casting/test_schema_casters.py
Although `str` and `bytes` act as sequences in Python, they do not count as arrays according to OpenAPI, so we should not allow them to validate as arrays.
=> Refuse to cast str or bytes to array

openapi_core/deserializing/parameters/factories.py, openapi_core/schema/parameters.py, tests/integration/validation/test_validators.py
Currently deepObjects are not supported, this PR adds that support.
Example spec
```yaml
components:
parameters:
exampleParameter:
name: paramObj
in: query
required: true
explode: true
style: deepObject
schema:
type: object
properties: 
count: 
type: integer
name:
type: string
```
Sadly it doesn't really fit in the `ParameterDeserializersFactory` ideology as it would never reach that step as  `get_value()` in [parameters.py](https://github.com/p1c2u/openapi-core/blob/master/openapi_core/schema/parameters.py#L42) would always fail as it tries to find the `name` of the `param_or_header` in the specific location. This is because how a deepObjects query param looks like (e.g. `someurl.com/?paramObj[count]=1&paramObj[name]=John`), the function would try to find `paramObj` in the location, …
=> Add deepObject support

openapi_core/schema/schemas.py, openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py, tests/unit/unmarshalling/test_validate.py
=> anyOf support

openapi_core/unmarshalling/schemas/unmarshallers.py
I've refactored the way how unmarshallers for `oneOf`/`anyOf` sub-schemas are created by using the [`SchemaUnmarshallersFactory`](https://github.com/p1c2u/openapi-core/blob/df4bbfe0d7b2a88e86f5f9a47d31549197717e47/openapi_core/unmarshalling/schemas/factories.py#L39-L121) instead of instantiating an `ObjectUnmarshaller` manually.
I believe this is what you were hinting at in https://github.com/p1c2u/openapi-core/pull/354/files#r979402096.
=> Create oneOf/anyOf unmarshaller using unmarshallers factory

docs/index.rst, docs/integrations.rst, openapi_core/contrib/starlette/__init__.py, openapi_core/contrib/starlette/requests.py, openapi_core/contrib/starlette/responses.py, openapi_core/schema/parameters.py, openapi_core/validation/request/datatypes.py, openapi_core/validation/response/protocols.py, openapi_core/validation/validators.py, poetry.lock, pyproject.toml, tests/integration/contrib/starlette/data/v3.0/starlette_factory.yaml, tests/integration/contrib/starlette/test_starlette_validation.py
=> Starlette support

openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py
Upgrading from 0.15.0 to 0.16.0 introduces the following crash when a list is sent as an "additional property" (aka. not part of the OpenAPI spec):
```
self = <jsonschema_spec.accessors.SpecAccessor object at 0x1030d12d0>, content = {}, parts_deque = deque([])
def _open(
self, content: Mapping[Hashable, Any], parts_deque: Deque[Hashable]
) -> Any:
if is_ref(content):
ref = content["$ref"]
with self.resolver.resolving(ref) as resolved:
return self._open(resolved, parts_deque)
try:
part = parts_deque.popleft()
except IndexError:
return content
else:
>           target = content[part]
E           KeyError: 'items'
content    = {}
part       = 'items'
parts_deque = deque([])
self       = <jsonschema_spec.accessors.SpecAccessor object at 0x1030d12d0>
```
This MR adds a test with a very basic …
=> Add failing test for lists as additional properties

openapi_core/unmarshalling/schemas/factories.py, openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py
The value 'null' is allowed in OpenAPI 3.1.
=> Add NullUnmarshaller

openapi_core/unmarshalling/schemas/unmarshallers.py, tests/integration/validation/test_petstore.py
=> additionalProperties without schema should allow null.

openapi_core/schema/schemas.py, openapi_core/unmarshalling/schemas/factories.py, openapi_core/unmarshalling/schemas/unmarshallers.py, poetry.lock, pyproject.toml, tests/integration/contrib/django/data/v3.0/djangoproject/pets/views.py, tests/integration/contrib/django/test_django_project.py, tests/integration/contrib/falcon/data/v3.0/falconproject/pets/resources.py, tests/integration/contrib/falcon/test_falcon_project.py, tests/integration/data/v3.0/petstore.yaml, tests/unit/unmarshalling/test_unmarshal.py
=> better unmarshaller finders with refactor

openapi_core/unmarshalling/schemas/factories.py, pyproject.toml
Avoid depend on backports.cached_property when the same function is available in functools.
=> Avoid dependency on modern python

docs/integrations.rst
In https://openapi-core.readthedocs.io/en/0.16.4/integrations.html the word **openapi_response_validator** is written without **n** in response, this PR fix this. So the import works.
=> fix typos in docs

README.rst, docs/integrations.rst, docs/usage.rst, openapi_core/validation/shortcuts.py, tests/integration/validation/test_petstore.py, tests/unit/validation/test_request_shortcuts.py, tests/unit/validation/test_response_shortcuts.py
Backward incompatibilities:
* `request` parameter for `validate_request` function moved to first position
* `request` and `response` parameters for `validate_response` function moved to first and second position
=> shortcuts high level public api expose

openapi_core/validation/request/exceptions.py, openapi_core/validation/request/validators.py
This reverts commit 3cc812f313da8a80a7dffbc9db6333f8c458fa5b, reversing changes made to 4945be0b4af028da451626c93e9979ba29658748.
=> ParametersError context property deprecated

openapi_core/contrib/django/requests.py, tests/unit/contrib/django/test_django.py
Django REST Framework will use `[^/.]+` as the default value pattern in certain cases, e.g. `(?P<pk>[^/.]+)`, which doesn't work well with the current regular expression in `PATH_PARAMETER_PATTERN`.
```
❯ git describe; git rev-parse HEAD
3.14.0-69-g0618fa88
0618fa88e1a8c2cf8a2aab29ef6de66b49e5f7ed
❯ git grep -n '\[^/.\]+'
rest_framework/routers.py:143:            self._default_value_pattern = '[^/.]+'
tests/test_routers.py:304:        expected = ['^notes/$', '^notes/(?P<pk>[^/.]+)/$']
tests/test_routers.py:319:        expected = ['^notes$', '^notes/(?P<pk>[^/.]+)$']
```
The fix inserts `(?:[^/]*?\[\^[^/]*/)?` before the final `[^/]*` in the pattern. This allows matching a slash inside an inverted character set, i.e. `[^...]`, treating it as part of the named group.
=> Fix PATH_PARAMETER_PATTERN for DRF default value pattern.

README.rst, docs/integrations.rst, docs/usage.rst, openapi_core/__init__.py, openapi_core/contrib/requests/__init__.py, openapi_core/contrib/requests/requests.py, openapi_core/security/providers.py, openapi_core/templating/paths/datatypes.py, openapi_core/templating/paths/finders.py, openapi_core/validation/processors.py, openapi_core/validation/request/__init__.py, openapi_core/validation/request/exceptions.py, openapi_core/validation/request/protocols.py, openapi_core/validation/request/proxies.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/__init__.py, openapi_core/validation/response/exceptions.py, openapi_core/validation/response/protocols.py, openapi_core/validation/response/proxies.py, openapi_core/validation/response/validators.py, openapi_core/validation/shortcuts.py, openapi_core/validation/validators.py, tests/integration/contrib/requests/data/v3.0/requests_factory.yaml, tests/integration/contrib/requests/test_requests_validation.py, tests/unit/security/test_providers.py, tests/unit/templating/test_paths_finders.py, tests/unit/validation/test_shortcuts.py
=> Webhooks support

openapi_core/contrib/django/handlers.py, openapi_core/contrib/falcon/handlers.py, openapi_core/contrib/flask/handlers.py, openapi_core/security/exceptions.py, openapi_core/security/providers.py, openapi_core/templating/security/exceptions.py, openapi_core/validation/datatypes.py, openapi_core/validation/decorators.py, openapi_core/validation/exceptions.py, openapi_core/validation/request/exceptions.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/exceptions.py, openapi_core/validation/response/validators.py, tests/integration/contrib/django/test_django_project.py, tests/integration/contrib/falcon/test_falcon_project.py, tests/integration/contrib/flask/test_flask_views.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/validation/test_petstore.py, tests/integration/validation/test_read_only_write_only.py, tests/integration/validation/test_security_override.py, tests/integration/validation/test_validators.py
Fixes #246
* All validation exceptions are subclasses of `ValidationError`
* All schema validation exceptions are subclass of `ValidateError`
* All request validation exceptions are subclass of `RequestError`
* All response validation exceptions are subclass of `ResponseError`
* `ParameterError` exceptions have name and location values.
* `HeaderError` exceptions have name value.
Backward compatibilities:
* Schema unmarshalling/validation returns `Invalid*` exception (`InvalidData`, `InvalidParameter`, `InvalidRequestBody`, `InvalidHeader`). Use `__cause__` property to get root cause exception.
* `InvalidSecurity` exception renamed to `SecurityNotFound`
=> Validation errors refactor

openapi_core/contrib/flask/decorators.py, tests/integration/contrib/flask/data/v3.0/flask_factory.yaml, tests/integration/contrib/flask/test_flask_decorator.py
=> Fix flask decorator function return other types

openapi_core/contrib/django/requests.py, openapi_core/contrib/django/responses.py, openapi_core/contrib/falcon/requests.py, openapi_core/contrib/falcon/responses.py, openapi_core/contrib/flask/requests.py, openapi_core/contrib/requests/requests.py, openapi_core/contrib/requests/responses.py, openapi_core/contrib/starlette/requests.py, openapi_core/contrib/starlette/responses.py, openapi_core/contrib/werkzeug/requests.py, openapi_core/contrib/werkzeug/responses.py, tests/unit/contrib/django/test_django.py, tests/unit/contrib/flask/test_flask_requests.py, tests/unit/contrib/flask/test_flask_responses.py, tests/unit/contrib/requests/test_requests_requests.py, tests/unit/contrib/requests/test_requests_responses.py
=> Fix integration Request Response factories check types fix

openapi_core/unmarshalling/schemas/exceptions.py
Randomly stumbled upon this when browsing the code.
=> Maaybe missing @dataclass decorator here?

openapi_core/contrib/requests/requests.py, tests/unit/contrib/requests/conftest.py, tests/unit/contrib/requests/test_requests_requests.py
Strip [valid](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) commends to prevent 
```
openapi_core.validation.response.exceptions.DataValidationError: DataValidationError: Content for the following mimetype not found: application/json; charset=utf-8. Valid mimetypes: ['application/json']"
```
=> strip Request mimetype

README.rst
The spelling of the word oficially is wrong, it should be corrected to officially
=> fix spelling in README.rst

openapi_core/shortcuts.py, poetry.lock, pyproject.toml, tests/integration/test_petstore.py, tests/unit/test_shortcuts.py
=> validate_request and validate_response return value deprecation fix

openapi_core/spec/paths.py, openapi_core/validation/schemas/factories.py, poetry.lock, pyproject.toml, tests/integration/conftest.py, tests/integration/schema/test_spec.py, tests/integration/unmarshalling/test_unmarshallers.py
Support for jsonschema 4.18, jsonschema-spec 0.2, openapi-schema-validator 0.6 and openapi-spec-validator 0.6
* `spec_url` parameter of `Spec.from_dict` is deprecated. Use `base_uri` instead.
* `ref_resolver_handlers` parameter of `Spec.from_dict` is deprecated. Use `handlers` instead.
=> jsonschema 4.18 compatibility

docs/integrations.rst, openapi_core/contrib/falcon/middlewares.py, openapi_core/contrib/flask/decorators.py, openapi_core/contrib/flask/views.py, openapi_core/unmarshalling/processors.py, openapi_core/validation/processors.py, tests/integration/contrib/falcon/data/v3.0/falconproject/openapi.py, tests/integration/contrib/flask/test_flask_decorator.py, tests/integration/contrib/flask/test_flask_views.py
Pass extra unmarshalling kwargs to unmarshalling processors (.`FalconOpenAPIMiddleware`, `FlaskOpenAPIView`, `FlaskOpenAPIViewDecorator`)
Fixes #618
=> Allow unmarshalling kwargs for unmarshalling processors

docs/integrations.rst, openapi_core/contrib/django/middlewares.py, openapi_core/contrib/falcon/middlewares.py, openapi_core/contrib/flask/__init__.py, openapi_core/contrib/flask/decorators.py, tests/integration/contrib/django/data/v3.0/djangoproject/tags/views.py, tests/integration/contrib/django/data/v3.0/djangoproject/urls.py, tests/integration/contrib/django/test_django_project.py, tests/integration/contrib/flask/conftest.py, tests/integration/contrib/flask/data/v3.0/flask_factory.yaml, tests/integration/contrib/flask/test_flask_decorator.py, tests/integration/contrib/flask/test_flask_validator.py, tests/integration/contrib/flask/test_flask_views.py
`response_cls` (`OPENAPI_RESPONSE_CLS` in Django) set to `None` skips response validation.
Fixes #662
=> Skip response validation option

openapi_core/contrib/django/handlers.py, openapi_core/contrib/django/middlewares.py, openapi_core/contrib/falcon/handlers.py, openapi_core/contrib/falcon/middlewares.py, openapi_core/contrib/flask/decorators.py, openapi_core/contrib/flask/handlers.py, openapi_core/contrib/flask/views.py, openapi_core/typing.py, openapi_core/unmarshalling/processors.py, openapi_core/unmarshalling/request/processors.py, openapi_core/unmarshalling/response/processors.py
`UnmarshallingProcessor` as a base for integration middleware/decorators
=> Unmarshalling processor enhancement

openapi_core/deserializing/media_types/deserializers.py, openapi_core/deserializing/media_types/factories.py, openapi_core/deserializing/media_types/util.py, openapi_core/templating/media_types/datatypes.py, openapi_core/templating/media_types/finders.py, openapi_core/validation/validators.py, tests/integration/test_petstore.py, tests/unit/deserializing/test_media_types_deserializers.py, tests/unit/templating/test_media_types_finders.py
=> Mimetype parameters handling

poetry.lock, pyproject.toml
I hope that I’ve done this in a way that fits the project’s usual workflow.
=> Allow openapi-spec-validator 0.7.x, and update it from 0.6.0 to 0.7.0

openapi_core/deserializing/media_types/__init__.py, openapi_core/deserializing/media_types/deserializers.py, openapi_core/deserializing/media_types/factories.py, openapi_core/deserializing/media_types/util.py, openapi_core/deserializing/styles/factories.py, openapi_core/schema/encodings.py, openapi_core/schema/parameters.py, openapi_core/validation/validators.py, tests/integration/test_petstore.py, tests/unit/deserializing/test_media_types_deserializers.py, tests/unit/deserializing/test_styles_deserializers.py
Changes result of deserialization for multipart media types.
`application/x-www-form-urlencoded` uses styles that required proper implementation.
Fixes #642
=> Media type encoding support

openapi_core/deserializing/media_types/deserializers.py, openapi_core/deserializing/media_types/util.py, tests/unit/deserializing/test_media_types_deserializers.py
=> Deserializing media type urlencoded content type

openapi_core/contrib/aiohttp/requests.py, openapi_core/contrib/aiohttp/responses.py, openapi_core/contrib/django/requests.py, openapi_core/contrib/django/responses.py, openapi_core/contrib/falcon/requests.py, openapi_core/contrib/falcon/responses.py, openapi_core/contrib/requests/requests.py, openapi_core/contrib/requests/responses.py, openapi_core/contrib/starlette/requests.py, openapi_core/contrib/starlette/responses.py, openapi_core/contrib/werkzeug/requests.py, openapi_core/contrib/werkzeug/responses.py, openapi_core/protocols.py, openapi_core/testing/requests.py, openapi_core/testing/responses.py, openapi_core/unmarshalling/request/unmarshallers.py, openapi_core/unmarshalling/response/unmarshallers.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/validators.py, tests/integration/test_petstore.py, tests/integration/unmarshalling/test_request_unmarshaller.py, tests/integration/unmarshalling/test_response_unmarshaller.py, tests/integration/validation/test_request_validators.py, tests/integration/validation/test_response_validators.py, tests/unit/contrib/django/test_django.py, tests/unit/contrib/flask/test_flask_requests.py, tests/unit/contrib/flask/test_flask_responses.py, tests/unit/contrib/requests/test_requests_requests.py, tests/unit/contrib/requests/test_requests_responses.py
Update Request and Response protocols. Move `mimetype` to `content_type` to include content parameters. Required to work with media type deserializing.
Backward incompatibility
=> Replace mimetype with content_type

openapi_core/casting/schemas/__init__.py, openapi_core/casting/schemas/casters.py, openapi_core/casting/schemas/factories.py, openapi_core/contrib/falcon/requests.py, openapi_core/unmarshalling/request/unmarshallers.py, openapi_core/unmarshalling/unmarshallers.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/validators.py, openapi_core/validation/validators.py, tests/integration/contrib/django/test_django_project.py, tests/integration/contrib/falcon/data/v3.0/falconproject/__main__.py, tests/integration/contrib/falcon/test_falcon_project.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/unmarshalling/test_request_unmarshaller.py, tests/integration/validation/test_request_validators.py, tests/unit/casting/test_schema_casters.py, tests/unit/test_shortcuts.py
=> Object caster

docs/integrations.rst, openapi_core/contrib/starlette/handlers.py, openapi_core/contrib/starlette/middlewares.py, openapi_core/contrib/starlette/requests.py, openapi_core/typing.py, openapi_core/unmarshalling/processors.py, poetry.lock, pyproject.toml, tests/integration/contrib/starlette/data/v3.0/starletteproject/__main__.py, tests/integration/contrib/starlette/data/v3.0/starletteproject/pets/endpoints.py, tests/integration/contrib/starlette/test_starlette_project.py, tests/integration/contrib/starlette/test_starlette_validation.py
Based on `AsyncUnmarshallingProcessor`
=> Starlette middleware

openapi_core/validation/request/validators.py, tests/integration/test_petstore.py
=> Validate empty request body fix

openapi_core/spec/paths.py, openapi_core/unmarshalling/schemas/unmarshallers.py, poetry.lock, pyproject.toml, tests/integration/contrib/django/data/v3.0/djangoproject/settings.py, tests/integration/contrib/requests/test_requests_validation.py, tests/integration/schema/test_spec.py, tests/integration/test_petstore.py, tests/integration/unmarshalling/test_request_unmarshaller.py, tests/integration/unmarshalling/test_unmarshallers.py, tests/unit/casting/test_schema_casters.py, tests/unit/conftest.py, tests/unit/deserializing/test_parameters_deserializers.py, tests/unit/extensions/test_factories.py, tests/unit/schema/test_schema_parameters.py, tests/unit/security/test_providers.py, tests/unit/templating/test_media_types_finders.py, tests/unit/templating/test_paths_finders.py, tests/unit/templating/test_responses_finders.py, tests/unit/test_paths_spec.py, tests/unit/unmarshalling/test_schema_unmarshallers.py, tests/unit/validation/test_schema_validators.py
Move from `validator` to `cis` for openapi -spec-validator
Fixes #715
=> Deprecated spec validator fix

openapi_core/testing/requests.py
Commit 0031ff74c04146fa6ba91925a7f54e0d5f7b2159 changed `data` from `str` to `bytes`, but forgot to adjust this default value.
=> Fix `MockRequest.body` type

openapi_core/app.py, openapi_core/unmarshalling/request/protocols.py, openapi_core/unmarshalling/response/protocols.py, openapi_core/validation/configurations.py, openapi_core/validation/request/protocols.py, openapi_core/validation/response/protocols.py
=> OpenAPI config passed to validators and unmarshallers fix

docs/integrations/fastapi.rst, docs/integrations/index.rst, openapi_core/contrib/fastapi/__init__.py, openapi_core/contrib/fastapi/middlewares.py, openapi_core/contrib/fastapi/requests.py, openapi_core/contrib/fastapi/responses.py, poetry.lock, pyproject.toml, tests/integration/contrib/fastapi/data/v3.0/fastapiproject/__main__.py, tests/integration/contrib/fastapi/data/v3.0/fastapiproject/openapi.py, tests/integration/contrib/fastapi/data/v3.0/fastapiproject/routers/pets.py, tests/integration/contrib/fastapi/test_fastapi_project.py
FastAPI requires `Starlette <0.28.0` but we need at least `Starlette => 0.32.0` because of `CachedRequest` for request's body buffer https://github.com/encode/starlette/pull/1692
=> FastAPI integration

tests/unit/test_shortcuts.py
Remove the spurious `pytest.warns()` contexts within `pytest.raises()` in `test_shortcuts`, in order to fix compatibility with pytest-8.0.0. Prior to this version, the exception raised caused these assertions to be ignored entirely.  This is fixed in pytest-8.0.0, and the tests start failing because the warning is never raised prior to the exception.
Fixes #789
=> Remove spurious `pytest.warns()` to fix pytest-8 compatibility

openapi_core/app.py, openapi_core/templating/paths/__init__.py, openapi_core/templating/paths/finders.py, openapi_core/templating/paths/iterators.py, openapi_core/templating/paths/protocols.py, openapi_core/templating/paths/types.py, openapi_core/unmarshalling/request/protocols.py, openapi_core/unmarshalling/request/unmarshallers.py, openapi_core/unmarshalling/response/protocols.py, openapi_core/unmarshalling/unmarshallers.py, openapi_core/validation/configurations.py, openapi_core/validation/request/protocols.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/protocols.py, openapi_core/validation/validators.py
=> Path finder cls configuration

openapi_core/templating/media_types/finders.py, tests/unit/templating/test_media_types_finders.py
Currently, the Content-Type header splits the media type from the parameters by looking for `; ` (a semicolon followed by a space), whereas according to [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-media-type) that space is optional.
This leads to issues when a client sends e.g. `application/json;charset=utf-8` which is valid as a Content Type header.
I used the examples from the RFC and made sure they are correctly handled. It isn't a full coverage of the allowed grammar, but hopefully it should cover most use cases.
=> Fix content-type when no space after semicolon

openapi_core/contrib/falcon/requests.py, openapi_core/contrib/falcon/util.py, tests/integration/contrib/falcon/data/v3.0/falconproject/pets/resources.py, tests/integration/contrib/falcon/test_falcon_project.py
=> Falcon multi-value query parameters fix

tests/integration/contrib/aiohttp/test_aiohttp_project.py
The warning says, “In v4, passing bytes will no longer create a file field. Please explicitly use the filename parameter or pass a BytesIO object.” This commit implements the latter approach.
=> Fix a DeprecationWarning from aiohttp in TestPetPhotoView

openapi_core/validation/schemas/factories.py, tests/integration/data/v3.0/parent-reference/openapi.yaml, tests/integration/data/v3.0/parent-reference/paths/books.yaml, tests/integration/data/v3.0/parent-reference/schemas/book.yaml, tests/integration/validation/test_parent_reference.py
=> Fix resolver for jsonschema validator created by `SchemaValidatorsFactory`

openapi_core/app.py, openapi_core/configurations.py
* Deprecate spec_base_uri
* Make `base_uri` as an option for non-path constructors
* Use `base_uri` from schema path for spec validation
Fixes #801
=> Deprecate `spec_base_uri`

openapi_core/unmarshalling/schemas/unmarshallers.py, openapi_core/validation/schemas/validators.py, tests/integration/unmarshalling/test_unmarshallers.py
=> Openapi 3.0 unmarshalling None with nullable subschema fix

docs/integrations/django.md, openapi_core/contrib/django/decorators.py, openapi_core/contrib/django/middlewares.py, openapi_core/contrib/django/providers.py, tests/integration/contrib/django/data/v3.0/djangoproject/status/views.py, tests/integration/contrib/django/data/v3.0/djangoproject/urls.py, tests/integration/contrib/django/test_django_project.py
Hello,
I have a project where I would like to be able to configure specifications for each view separately, because we have several API variants, and therefore several specification files.
This is very inspired by the approach used by Flask integrations.
Best regards,
Kamil Breguła
=> Add django decorator

poetry.lock, pyproject.toml
Starlette 0.45 drops Python 3.8 support, removes `ExceptionMiddleware` from `starlette.exceptions`, and removes `WS_1004_NO_STATUS_RCVD` and `WS_1005_ABNORMAL_CLOSURE`: https://github.com/encode/starlette/releases/tag/0.45.0
Starlette 0.46 renames `max_file_size` to `spool_max_size` in `MultiPartParser`: https://github.com/encode/starlette/releases/tag/0.46.0
None of that should affect openapi-core.
----
Even with this PR, Starlette would still be stuck at `0.44.0` in `poetry.lock` until openapi-core drops support for Python 3.8.
I didn’t try to drop Python 3.8 support in this PR, but just to check, I tried a local experiment:
```diff
diff --git a/pyproject.toml b/pyproject.toml
index 8132fd5..16369f9 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -47,7 +47,6 @@ classifiers = [ …
```
=> Allow Starlette 0.45 and 0.46
