openapi_core/media_types.py, openapi_core/request_bodies.py, openapi_core/wrappers.py, tests/integration/test_petstore.py, tests/unit/test_request_bodies.py
Content-type is something more (encoding etc.) than just media-type (mimetype).
=> Content_type renamed to mimetype

README.rst, openapi_core/exceptions.py, openapi_core/operations.py, openapi_core/parameters.py, openapi_core/responses.py, openapi_core/validators.py, openapi_core/wrappers.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_validators.py, tests/integration/test_wrappers.py, tests/unit/test_operations.py
=> Responses validation

openapi_core/enums.py, openapi_core/parameters.py, openapi_core/schemas.py, openapi_core/validators.py, openapi_core/wrappers.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py, tests/integration/test_wrappers.py, tests/unit/test_paramters.py
Support for `style` and `explode` parameter values
=> Serialized parameters support

openapi_core/shortcuts.py, setup.py, tests/unit/test_shortcuts.py
=> Werkzeug as extra requirement fix

openapi_core/__init__.py
=> validate_data shortcut import fix

openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py
=> Schema format accepts any value

openapi_core/schema/schemas/factories.py, openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py
=> Schema additional properties support

openapi_core/schema/content/exceptions.py, openapi_core/schema/content/models.py, openapi_core/schema/request_bodies/models.py, openapi_core/schema/responses/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py
=> Mimetype wildcards support

openapi_core/schema/operations/generators.py, tests/integration/test_petstore.py
=> Populate operation_id attribute

openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/util.py, tests/unit/schema/test_schemas.py
I added date formatter since it cloud be implemented with built-in function.
Fixes #56
=> Support unmarshaling string with format keyword

openapi_core/schema/media_types/models.py, openapi_core/schema/parameters/models.py, openapi_core/schema/responses/models.py, openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/validators.py, tests/unit/schema/test_schemas.py
Fixes #53
It will allow to run schema validation for value without casting.
=> Separate schema casting and validation

openapi_core/extensions/models/factories.py, openapi_core/extensions/models/models.py, openapi_core/schema/schemas/models.py, tests/integration/test_petstore.py, tests/integration/test_validators.py, tests/unit/extensions/test_models.py, tests/unit/schema/test_schemas.py
Separate object validation and object unmarshalling.
Return true object (BaseModel)
=> Object validation

openapi_core/schema/schemas/models.py, openapi_core/schema/schemas/util.py, tests/integration/data/v3.0/petstore.yaml, tests/unit/schema/test_schemas.py
=> String validation

openapi_core/schema/schemas/enums.py, openapi_core/schema/schemas/exceptions.py, openapi_core/schema/schemas/factories.py, openapi_core/schema/schemas/models.py, tests/integration/data/v3.0/petstore.yaml, tests/integration/test_petstore.py
Related to #36 
It's a first step to support oneof
=> Any schema type

openapi_core/schema/content/exceptions.py, openapi_core/schema/content/models.py, openapi_core/schema/media_types/exceptions.py, openapi_core/schema/media_types/models.py, openapi_core/schema/operations/exceptions.py, openapi_core/schema/operations/models.py, openapi_core/schema/parameters/exceptions.py, openapi_core/schema/parameters/models.py, openapi_core/schema/request_bodies/exceptions.py, openapi_core/schema/request_bodies/models.py, openapi_core/schema/responses/exceptions.py, openapi_core/schema/responses/models.py, openapi_core/schema/schemas/exceptions.py, openapi_core/schema/schemas/models.py, openapi_core/schema/servers/exceptions.py, openapi_core/schema/specs/models.py, openapi_core/validation/request/validators.py, openapi_core/validation/response/validators.py, requirements.txt, requirements_2.7.txt, setup.py, tests/integration/test_petstore.py
PS: This uses https://github.com/p1c2u/openapi-core/pull/89 as a base just in hope not to have to deal with conflicts twice :)
=> Structured exceptions

openapi_core/schema/schemas/models.py
otherwise Falsy values are not valid types
=> Dont use value for determining any type

README.rst, openapi_core/shortcuts.py
=> Validators shortcuts fix

README.rst
I decided to roll a plugin that leverages your library for providing OpenAPI 3 support in Bottle. I don't know if you're interested in having it listed as another integration or not, but since there's no existing Bottle integration, I figured it might be useful for someone else like me that still uses Bottle.
=> Added a link to a Bottle plugin that leverages OpenAPI Core

.github/workflows/python-publish.yml, .github/workflows/python-test.yml, .travis.yml
* run python tests
* publish python package
=> GitHub actions

openapi_core/unmarshalling/schemas/unmarshallers.py, tests/unit/unmarshalling/test_unmarshal.py
=> Any unmarshaller validate fix

.github/workflows/python-test.yml, setup.cfg
=> openapi-spec-validator strict requirement fix

openapi_core/contrib/flask/requests.py, openapi_core/contrib/werkzeug/requests.py, tests/integration/contrib/flask/test_flask_validator.py, tests/integration/contrib/werkzeug/test_werkzeug_validation.py
=> werkzeug flask root path fix

poetry.lock, pyproject.toml
=> allow openapi-schema-validator 0.4

openapi_core/validation/request/exceptions.py, openapi_core/validation/request/validators.py
This reverts commit ae087580b7adb049deb27e0e110a74bfb23259b2, reversing changes made to 6f911802226e8332f0dec0332f6d89ad23e1872c.
We will reintroduce the change later in major change.
=> Revert of "ParametersError context property deprecated"

openapi_core/contrib/requests/requests.py, tests/unit/contrib/requests/test_requests_requests.py
=> Fix Requests request dont allow fragments

poetry.lock, tests/unit/unmarshalling/test_validate.py
Fixes https://github.com/python-openapi/openapi-core/issues/525
=> openapi-schema-validator 0.5.2 tests compatibility fix

openapi_core/spec/paths.py, openapi_core/templating/paths/exceptions.py, openapi_core/templating/paths/finders.py, tests/unit/templating/test_paths_finders.py
Error for spec without path (spec 3.1 without web hooks defined)
=> paths not found fix

openapi_core/validation/schemas/validators.py, tests/integration/validation/test_parent_reference.py
=> Fix resolvers not updating properly when referencing other files.

docs/integrations/requests.rst
Include the import examples to make it explicit (Explicit is better than implicit) and fix a small typo in the code.
=> Improve Requests integration documentation

openapi_core/unmarshalling/request/datatypes.py
=> RequestUnmarshalResult body type fix
